service: iCompaas

frameworkVersion: '2'

custom:
  wsgi:
    app: iCompaas.wsgi.application

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
